### ISSUE TITLE
Trying to contact you regarding the woodpecker board

### ISSUE THREAD

**Issue by luiscabus** [CONSULitAS/Marlin-K8200#1]
Hi,

I have the same CNC board, woodpecker 3.0~. I'm trying to figure out how to wire endstops to be able to autohome it. Did you try this yet?

**Comment by CONSULitAS** [comment]
offtopic

**Comment by CONSULitAS** [comment]
> I have the same CNC board, woodpecker 3.0~. I'm trying to figure out how to wire endstops to be able to autohome it. Did you try this yet?

No, I didn't try. But it is rather easy:
* connect micro switch to Xen, Yen, Zen and the corresponding GND
* others have done this
  * https://www.thingiverse.com/CONSULitAS/collections/cnc-3018-2418-2410-and-1610
  * eg https://www.thingiverse.com/thing:2796202 the mounts
* configure $20 to $27
  * https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9
  * example here: https://www.thingiverse.com/thing:2633933
* play!

**Comment by CONSULitAS** [comment]
@luiscabus 
Further discussions:
Just google my company name and send an email to the easy to find address.
You are welcome. 😄
